#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSAddress
@end

@interface CSAddress : CSObject

/* Your address name. 
 */
@property(nonatomic) NSString* addressName;
/* Your address line 1 
 */
@property(nonatomic) NSString* addressLine1;
/* Your city 
 */
@property(nonatomic) NSString* addressCity;
/* Your postal code 
 */
@property(nonatomic) NSString* addressPostalCode;
/* Your country 
 */
@property(nonatomic) NSString* addressCountry;
/* Your address line 2 [optional]
 */
@property(nonatomic) NSString* addressLine2;
/* Your state [optional]
 */
@property(nonatomic) NSString* addressState;

@end
