#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSAttachment
@end

@interface CSAttachment : CSObject

/* The base64-encoded contents of the file. 
 */
@property(nonatomic) NSString* content;
/* The type of file being attached. 
 */
@property(nonatomic) NSString* type;
/* The name of the file being attached. 
 */
@property(nonatomic) NSString* filename;
/* Inline for content that can be displayed within the email, or attachment for any other files. 
 */
@property(nonatomic) NSString* disposition;
/* An ID for the content. 
 */
@property(nonatomic) NSString* contentId;

@end
