#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSContact
@end

@interface CSContact : CSObject

/* Your phone number in E.164 format. Must be provided if no fax number or email. 
 */
@property(nonatomic) NSString* phoneNumber;
/*  
 */
@property(nonatomic) NSString* custom1;
/* Your email. Must be provided if no phone number or fax number. [optional]
 */
@property(nonatomic) NSString* email;
/* Your fax number. Must be provided if no phone number or email. [optional]
 */
@property(nonatomic) NSString* faxNumber;
/* Your first name. [optional]
 */
@property(nonatomic) NSString* firstName;
/* Your street address [optional]
 */
@property(nonatomic) NSString* addressLine1;
/*  [optional]
 */
@property(nonatomic) NSString* addressLine2;
/* Your nearest city [optional]
 */
@property(nonatomic) NSString* addressCity;
/* Your current state [optional]
 */
@property(nonatomic) NSString* addressState;
/* Your current postcode [optional]
 */
@property(nonatomic) NSString* addressPostalCode;
/* Your current country [optional]
 */
@property(nonatomic) NSString* addressCountry;
/* Your organisation name [optional]
 */
@property(nonatomic) NSString* organizationName;
/*  [optional]
 */
@property(nonatomic) NSString* custom2;
/*  [optional]
 */
@property(nonatomic) NSString* custom3;
/*  [optional]
 */
@property(nonatomic) NSString* custom4;
/* Your last name [optional]
 */
@property(nonatomic) NSString* lastName;

@end
