#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSCreditCard
@end

@interface CSCreditCard : CSObject

/* Credit card number 
 */
@property(nonatomic) NSString* number;
/* Expiry month of credit card 
 */
@property(nonatomic) NSNumber* expiryMonth;
/* Expiry year of credit card 
 */
@property(nonatomic) NSNumber* expiryYear;
/* CVC number of credit card 
 */
@property(nonatomic) NSNumber* cvc;
/* Name printed on credit card 
 */
@property(nonatomic) NSString* name;
/* Name of bank that credit card belongs to 
 */
@property(nonatomic) NSString* bankName;

@end
