#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CSAttachment.h"
#import "CSEmailFrom.h"
#import "CSEmailRecipient.h"
@protocol CSAttachment;
@class CSAttachment;
@protocol CSEmailFrom;
@class CSEmailFrom;
@protocol CSEmailRecipient;
@class CSEmailRecipient;



@protocol CSEmail
@end

@interface CSEmail : CSObject

/* Array of To Recipient items. 
 */
@property(nonatomic) NSArray<CSEmailRecipient>* to;
/* Array of Cc Recipient items. [optional]
 */
@property(nonatomic) NSArray<CSEmailRecipient>* cc;
/* Array of Bcc Recipient items. [optional]
 */
@property(nonatomic) NSArray<CSEmailRecipient>* bcc;

@property(nonatomic) CSEmailFrom* from;
/* Subject of the email. [optional]
 */
@property(nonatomic) NSString* subject;
/* Body of the email. 
 */
@property(nonatomic) NSString* body;
/* Array of Attachment items. [optional]
 */
@property(nonatomic) NSArray<CSAttachment>* attachments;
/* Schedule. [optional]
 */
@property(nonatomic) NSNumber* schedule;

@end
