#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSEmailCampaign
@end

@interface CSEmailCampaign : CSObject

/* Your campaign name. 
 */
@property(nonatomic) NSString* name;
/* Your campaign subject. 
 */
@property(nonatomic) NSString* subject;
/* Your campaign message. 
 */
@property(nonatomic) NSString* body;
/* The allowed email address id. 
 */
@property(nonatomic) NSNumber* fromEmailAddressId;
/* Your name or business name. 
 */
@property(nonatomic) NSString* fromName;
/* Your template id. [optional]
 */
@property(nonatomic) NSNumber* templateId;
/* Your contact list id. 
 */
@property(nonatomic) NSNumber* listId;
/* Your schedule timestamp. [optional]
 */
@property(nonatomic) NSNumber* schedule;

@end
