#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CSFaxMessage.h"
@protocol CSFaxMessage;
@class CSFaxMessage;



@protocol CSFaxMessageCollection
@end

@interface CSFaxMessageCollection : CSObject

/* Array of FaxMessage items 
 */
@property(nonatomic) NSArray<CSFaxMessage>* messages;
/* URL of file to send 
 */
@property(nonatomic) NSString* fileUrl;

@end
