#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSInboundFaxRule
@end

@interface CSInboundFaxRule : CSObject

/* Dedicated Number. Can be '*' to apply to all numbers. 
 */
@property(nonatomic) NSString* dedicatedNumber;
/* Rule Name. 
 */
@property(nonatomic) NSString* ruleName;
/* Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). 
 */
@property(nonatomic) NSString* action;
/* Action address. 
 */
@property(nonatomic) NSString* actionAddress;
/* Enabled: Disabled=0 or Enabled=1. 
 */
@property(nonatomic) NSNumber* enabled;

@end
