#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSMmsMessage
@end

@interface CSMmsMessage : CSObject

/* Recipient phone number in E.164 format [optional]
 */
@property(nonatomic) NSString* to;
/* Your message 
 */
@property(nonatomic) NSString* body;
/* Subject line (max 20 characters) 
 */
@property(nonatomic) NSString* subject;
/* Your sender ID [optional]
 */
@property(nonatomic) NSString* from;
/* Recipient country [optional]
 */
@property(nonatomic) NSString* country;
/* Your method of sending [optional]
 */
@property(nonatomic) NSString* source;
/* Your list ID if sending to a whole list (can be used instead of 'to') [optional]
 */
@property(nonatomic) NSNumber* listId;
/* Schedule time in unix format (leave blank for immediate delivery) [optional]
 */
@property(nonatomic) NSNumber* schedule;
/* Custom string for your reference [optional]
 */
@property(nonatomic) NSString* customString;
/* Email to send replies to [optional]
 */
@property(nonatomic) NSString* fromEmail;

@end
