#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CSPostDirectMailArea.h"
@protocol CSPostDirectMailArea;
@class CSPostDirectMailArea;



@protocol CSPostDirectMail
@end

@interface CSPostDirectMail : CSObject

/* Campaign name 
 */
@property(nonatomic) NSString* name;
/* Campaign file URLs (maximum 2) 
 */
@property(nonatomic) NSArray<NSString*>* fileUrls;
/* Document size - A5 or DL 
 */
@property(nonatomic) NSString* size;
/* PostDirectMailArea model 
 */
@property(nonatomic) NSArray<CSPostDirectMailArea>* areas;
/* Leave blank for immediate delivery. Your schedule time in unix format. [optional]
 */
@property(nonatomic) NSNumber* schedule;
/* Your method of sending e.g. 'wordpress', 'php', 'c#'. [optional]
 */
@property(nonatomic) NSString* source;
/* A custom string for your own reference [optional]
 */
@property(nonatomic) NSString* customString;

@end
