#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSPostRecipient
@end

@interface CSPostRecipient : CSObject

/* Name of address 
 */
@property(nonatomic) NSString* addressName;
/* First line of address 
 */
@property(nonatomic) NSString* addressLine1;
/* Second line of address [optional]
 */
@property(nonatomic) NSString* addressLine2;
/* City 
 */
@property(nonatomic) NSString* addressCity;
/* State 
 */
@property(nonatomic) NSString* addressState;
/* Postal code 
 */
@property(nonatomic) NSString* addressPostalCode;
/* Country 
 */
@property(nonatomic) NSString* addressCountry;
/* ID of return address to use 
 */
@property(nonatomic) NSNumber* returnAddressId;
/* When to send letter (0/null=now) [optional]
 */
@property(nonatomic) NSNumber* schedule;

@end
