#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 API
*  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
*
* OpenAPI spec version: 3.1
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSResellerAccount
@end

@interface CSResellerAccount : CSObject

/* Account username 
 */
@property(nonatomic) NSString* username;
/* Account password (unhashed) 
 */
@property(nonatomic) NSString* password;
/* Account email 
 */
@property(nonatomic) NSString* userEmail;
/* Account phone number 
 */
@property(nonatomic) NSString* userPhone;
/* Account owner first name 
 */
@property(nonatomic) NSString* userFirstName;
/* Account owner last name 
 */
@property(nonatomic) NSString* userLastName;
/* Account name (usually company name) 
 */
@property(nonatomic) NSString* accountName;
/* Country of account holder 
 */
@property(nonatomic) NSString* country;

@end
