#import <Foundation/Foundation.h>
#import "CSObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CSSubaccount
@end

@interface CSSubaccount : CSObject

/* Your new api username. 
 */
@property(nonatomic) NSString* apiUsername;
/* Your new password 
 */
@property(nonatomic) NSString* password;
/* Your new email. 
 */
@property(nonatomic) NSString* email;
/* Your phone number in E.164 format. 
 */
@property(nonatomic) NSString* phoneNumber;
/* Your firstname 
 */
@property(nonatomic) NSString* firstName;
/* Your lastname 
 */
@property(nonatomic) NSString* lastName;
/* Your access users flag value, must be 1 or 0. [optional]
 */
@property(nonatomic) NSNumber* accessUsers;
/* Your access billing flag value, must be 1 or 0. [optional]
 */
@property(nonatomic) NSNumber* accessBilling;
/* Your access reporting flag value, must be 1 or 0. [optional]
 */
@property(nonatomic) NSNumber* accessReporting;
/* Your access contacts flag value, must be 1 or 0. [optional]
 */
@property(nonatomic) NSNumber* accessContacts;
/* Your access settings flag value, must be 1 or 0. [optional]
 */
@property(nonatomic) NSNumber* accessSettings;

@end
