#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCreditCard
@end

@interface SWGCreditCard : SWGObject

/* Credit card number 
 */
@property(nonatomic) NSString* number;
/* Expiry month of credit card 
 */
@property(nonatomic) NSNumber* expiryMonth;
/* Expiry year of credit card 
 */
@property(nonatomic) NSNumber* expiryYear;
/* CVC number of credit card 
 */
@property(nonatomic) NSNumber* cvc;
/* Name printed on credit card 
 */
@property(nonatomic) NSString* name;
/* Name of bank that credit card belongs to 
 */
@property(nonatomic) NSString* bankName;

@end
