#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGDeliveryIssue
@end

@interface SWGDeliveryIssue : SWGObject

/* The message id of the message. [optional]
 */
@property(nonatomic) NSString* messageId;
/* The type of message, must be one of the following values SMS, MMS, VOICE, EMAIL_MARKETING, EMAIL_TRANSACTIONAL, FAX, POST. 
 */
@property(nonatomic) NSString* type;
/* The description of the message. 
 */
@property(nonatomic) NSString* _description;
/* The user's comments. [optional]
 */
@property(nonatomic) NSString* clientComments;
/* The user's email address. 
 */
@property(nonatomic) NSString* emailAddress;

@end
