#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGEmailCampaign
@end

@interface SWGEmailCampaign : SWGObject

/* Your campaign name. 
 */
@property(nonatomic) NSString* name;
/* Your campaign subject. 
 */
@property(nonatomic) NSString* subject;
/* Your campaign message. 
 */
@property(nonatomic) NSString* body;
/* The allowed email address id. 
 */
@property(nonatomic) NSNumber* fromEmailAddressId;
/* Your name or business name. 
 */
@property(nonatomic) NSString* fromName;
/* Your template id. [optional]
 */
@property(nonatomic) NSNumber* templateId;
/* Your contact list id. 
 */
@property(nonatomic) NSNumber* listId;
/* Your schedule timestamp. [optional]
 */
@property(nonatomic) NSNumber* schedule;

@end
