#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInboundFAXRule
@end

@interface SWGInboundFAXRule : SWGObject

/* Dedicated Number. Can be '*' to apply to all numbers. 
 */
@property(nonatomic) NSString* dedicatedNumber;
/* Rule Name. 
 */
@property(nonatomic) NSString* ruleName;
/* Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). 
 */
@property(nonatomic) NSString* action;
/* Action address. 
 */
@property(nonatomic) NSString* actionAddress;
/* Enabled: Disabled=0 or Enabled=1. 
 */
@property(nonatomic) NSNumber* enabled;

@end
