#import <Foundation/Foundation.h>
#import "CSSmsCampaign.h"
#import "CSApi.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CSSmsCampaignApi: NSObject <CSApi>

extern NSString* kCSSmsCampaignApiErrorDomain;
extern NSInteger kCSSmsCampaignApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CSApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get specific sms campaign
/// Get specific sms campaign
///
/// @param smsCampaignId ID of SMS campaign to retrieve
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsCampaignBySmsCampaignIdGetWithSmsCampaignId: (NSNumber*) smsCampaignId
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Update sms campaign
/// Update sms campaign
///
/// @param smsCampaignId ID of SMS campaign to update
/// @param campaign SmsCampaign model
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsCampaignsBySmsCampaignIdPutWithSmsCampaignId: (NSNumber*) smsCampaignId
    campaign: (CSSmsCampaign*) campaign
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Cancel sms campaign
/// Cancel sms campaign
///
/// @param smsCampaignId ID of SMS Campaign to cancel
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsCampaignsCancelBySmsCampaignIdPutWithSmsCampaignId: (NSNumber*) smsCampaignId
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get list of sms campaigns
/// Get list of sms campaigns
///
/// @param page Page number (optional) (default to 1)
/// @param limit Number of records per page (optional) (default to 10)
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsCampaignsGetWithPage: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Calculate price for sms campaign
/// Calculate price for sms campaign
///
/// @param campaign SmsCampaign model
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsCampaignsPricePostWithCampaign: (CSSmsCampaign*) campaign
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Create sms campaign
/// Create sms campaign
///
/// @param campaign SmsCampaign model
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsCampaignsSendPostWithCampaign: (CSSmsCampaign*) campaign
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
