#import <Foundation/Foundation.h>
#import "SWGDeliveryReceiptRule.h"
#import "SWGApi.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGSMSDeliveryReceiptRulesApi: NSObject <SWGApi>

extern NSString* kSWGSMSDeliveryReceiptRulesApiErrorDomain;
extern NSInteger kSWGSMSDeliveryReceiptRulesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Delete sms delivery receipt automation
/// Delete sms delivery receipt automation
///
/// @param receiptRuleId Receipt rule id
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsDeliveryReceiptAutomationDeleteWithReceiptRuleId: (NSNumber*) receiptRuleId
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get specific sms delivery receipt automation
/// Get specific sms delivery receipt automation
///
/// @param receiptRuleId Receipt rule id
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsDeliveryReceiptAutomationGetWithReceiptRuleId: (NSNumber*) receiptRuleId
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Create sms delivery receipt automations
/// Create sms delivery receipt automations
///
/// @param deliveryReceiptRule sms delivery receipt rule model
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsDeliveryReceiptAutomationPostWithDeliveryReceiptRule: (SWGDeliveryReceiptRule*) deliveryReceiptRule
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Update sms delivery receipt automation
/// Update sms delivery receipt automation
///
/// @param receiptRuleId Receipt rule id
/// @param deliveryReceiptRule Delivery receipt rule model
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsDeliveryReceiptAutomationPutWithReceiptRuleId: (NSNumber*) receiptRuleId
    deliveryReceiptRule: (SWGDeliveryReceiptRule*) deliveryReceiptRule
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get all sms delivery receipt automations
/// Get all sms delivery receipt automations
///
/// @param page Page number (optional) (default to 1)
/// @param limit Number of records per page (optional) (default to 10)
/// 
///  code:200 message:"SUCCESS",
///  code:400 message:"BAD_REQUEST",
///  code:401 message:"UNAUTHORIZED",
///  code:403 message:"FORBIDDEN",
///  code:404 message:"NOT_FOUND",
///  code:405 message:"METHOD_NOT_FOUND",
///  code:429 message:"TOO_MANY_REQUESTS",
///  code:0 message:"INTERNAL_SERVER_ERROR"
///
/// @return NSString*
-(NSURLSessionTask*) smsDeliveryReceiptAutomationsGetWithPage: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
