#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAttachment.h"
#import "SWGEmailFrom.h"
#import "SWGEmailRecipient.h"
@protocol SWGAttachment;
@class SWGAttachment;
@protocol SWGEmailFrom;
@class SWGEmailFrom;
@protocol SWGEmailRecipient;
@class SWGEmailRecipient;



@protocol SWGEmail
@end

@interface SWGEmail : SWGObject

/* Array of To Recipient items. 
 */
@property(nonatomic) NSArray<SWGEmailRecipient>* to;
/* Array of Cc Recipient items. [optional]
 */
@property(nonatomic) NSArray<SWGEmailRecipient>* cc;
/* Array of Bcc Recipient items. [optional]
 */
@property(nonatomic) NSArray<SWGEmailRecipient>* bcc;
/* From Email object. 
 */
@property(nonatomic) NSArray<SWGEmailFrom>* from;
/* Body of the email. 
 */
@property(nonatomic) NSString* body;
/* Array of Attachment items. [optional]
 */
@property(nonatomic) NSArray<SWGAttachment>* attachments;
/* Schedule. [optional]
 */
@property(nonatomic) NSNumber* schedule;

@end
