#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* ClickSend v3 REST API
*  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
*
* OpenAPI spec version: 3.1.0
* Contact: support@clicksend.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGFaxMessage
@end

@interface SWGFaxMessage : SWGObject

/* Your method of sending e.g. 'wordpress', 'php', 'c#'. [optional]
 */
@property(nonatomic) NSString* source;
/* Recipient fax number in E.164 format. 
 */
@property(nonatomic) NSString* to;
/* Your list ID if sending to a whole list. Can be used instead of 'to'. [optional]
 */
@property(nonatomic) NSNumber* listId;
/* Your sender id. Must be a valid fax number. [optional]
 */
@property(nonatomic) NSString* from;
/* Leave blank for immediate delivery. Your schedule time in unix format http://help.clicksend.com/what-is-a-unix-timestamp [optional]
 */
@property(nonatomic) NSNumber* schedule;
/* Your reference. Will be passed back with all replies and delivery reports. [optional]
 */
@property(nonatomic) NSString* customString;
/* Recipient country. [optional]
 */
@property(nonatomic) NSString* country;
/* An email address where the reply should be emailed to. [optional]
 */
@property(nonatomic) NSString* fromEmail;

@end
